#!/usr/bin/env bash
set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
output_file="$SCRIPT_DIR/../docker-compose.local.override.yml"

mounts=""

add_mount() {
    host_path=$1
    target_path=$2

    if [ -e "$host_path" ]; then
        if [ -n "$mounts" ]; then
            mounts="${mounts}      - \"${host_path}:${target_path}\"\n"
        else
            mounts="      - \"${host_path}:${target_path}\"\n"
        fi
    fi
}

add_ro_mount() {
    host_path=$1
    target_path=$2

    if [ -e "$host_path" ]; then
        if [ -n "$mounts" ]; then
            mounts="${mounts}      - \"${host_path}:${target_path}:ro\"\n"
        else
            mounts="      - \"${host_path}:${target_path}:ro\"\n"
        fi
    fi
}

add_mount "$HOME/.codex" "/home/ubuntu/.codex"
add_mount "$HOME/.claude" "/home/ubuntu/.claude"
add_mount "$HOME/.claude.json" "/home/ubuntu/.claude.json"
add_mount "$HOME/.lark-cli" "/home/ubuntu/.lark-cli"
add_mount "$HOME/.config/opencode" "/home/ubuntu/.config/opencode"
add_mount "$HOME/.local/share/lark-cli" "/home/ubuntu/.local/share/lark-cli"
add_mount "$HOME/.local/share/opencode" "/home/ubuntu/.local/share/opencode"
add_ro_mount "$HOME/.agents/skills" "/home/ubuntu/.agents/skills"

{
    printf '%s\n' '# Generated by generate-local-override.sh - do not commit'
    printf '%s\n' 'services:'
    printf '%s\n' '  librmcs-develop:'
    printf '%s\n' '    volumes:'
    if [ -n "$mounts" ]; then
        printf '%b' "$mounts"
    else
        printf '%s\n' '      []'
    fi
} > "$output_file"
