#!/usr/bin/env bash
set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
output_file="$SCRIPT_DIR/../docker-compose.local.override.yml"
repo_root="$(cd "$SCRIPT_DIR/../.." && pwd)"

mounts=""
environment_entries=""

add_mount() {
    host_path=$1
    target_path=$2

    if [ -e "$host_path" ]; then
        if [ -n "$mounts" ]; then
            mounts="${mounts}      - \"${host_path}:${target_path}\"\n"
        else
            mounts="      - \"${host_path}:${target_path}\"\n"
        fi
    fi
}

add_ro_mount() {
    host_path=$1
    target_path=$2

    if [ -e "$host_path" ]; then
        if [ -n "$mounts" ]; then
            mounts="${mounts}      - \"${host_path}:${target_path}:ro\"\n"
        else
            mounts="      - \"${host_path}:${target_path}:ro\"\n"
        fi
    fi
}

add_env() {
    env_name=$1
    env_value=$2

    if [ -n "$environment_entries" ]; then
        environment_entries="${environment_entries}      ${env_name}: \"${env_value}\"\n"
    else
        environment_entries="      ${env_name}: \"${env_value}\"\n"
    fi
}

add_mount "$HOME/.codex" "/home/ubuntu/.codex"
add_mount "$HOME/.claude" "/home/ubuntu/.claude"
add_mount "$HOME/.claude.json" "/home/ubuntu/.claude.json"
add_mount "$HOME/.lark-cli" "/home/ubuntu/.lark-cli"
add_mount "$HOME/.config/opencode" "/home/ubuntu/.config/opencode"
add_mount "$HOME/.local/share/lark-cli" "/home/ubuntu/.local/share/lark-cli"
add_mount "$HOME/.local/share/opencode" "/home/ubuntu/.local/share/opencode"
add_ro_mount "$HOME/.agents/skills" "/home/ubuntu/.agents/skills"

add_env "HOST_WORKSPACE_FOLDER" "$repo_root"

if [ -n "${DISPLAY:-}" ]; then
    add_env "DISPLAY" "$DISPLAY"
fi
if [ -n "${HTTP_PROXY:-}" ]; then
    add_env "HTTP_PROXY" "$HTTP_PROXY"
fi
if [ -n "${HTTPS_PROXY:-}" ]; then
    add_env "HTTPS_PROXY" "$HTTPS_PROXY"
fi
if [ -n "${NO_PROXY:-}" ]; then
    add_env "NO_PROXY" "$NO_PROXY"
fi
if [ -n "${http_proxy:-}" ]; then
    add_env "http_proxy" "$http_proxy"
fi
if [ -n "${https_proxy:-}" ]; then
    add_env "https_proxy" "$https_proxy"
fi
if [ -n "${no_proxy:-}" ]; then
    add_env "no_proxy" "$no_proxy"
fi

{
    printf '%s\n' '# Generated by generate-local-override.sh - do not commit'
    printf '%s\n' 'services:'
    printf '%s\n' '  librmcs-develop:'
    if [ -n "$environment_entries" ]; then
        printf '%s\n' '    environment:'
        printf '%b' "$environment_entries"
    fi
    printf '%s\n' '    volumes:'
    if [ -n "$mounts" ]; then
        printf '%b' "$mounts"
    else
        printf '%s\n' '      []'
    fi
} > "$output_file"
